/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_syy_studio_player_Player */

#ifndef _Included_com_syy_studio_player_Player
#define _Included_com_syy_studio_player_Player
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_syy_studio_player_Player
 * Method:    onSurfaceCreated
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_syy_studio_player_Player_onSurfaceCreated
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_syy_studio_player_Player
 * Method:    onSurfaceDestroyed
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_syy_studio_player_Player_onSurfaceDestroyed
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_syy_studio_player_Player
 * Method:    prepare
 * Signature: (Ljava/lang/String;[IIIZFFIILandroid/view/Surface;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_syy_studio_player_Player_prepare
  (JNIEnv *, jobject, jstring, jintArray, jint, jint, jboolean, jfloat, jfloat, jint, jint, jobject);

/*
 * Class:     com_syy_studio_player_Player
 * Method:    pause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_syy_studio_player_Player_pause
  (JNIEnv *, jobject);

/*
 * Class:     com_syy_studio_player_Player
 * Method:    play
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_syy_studio_player_Player_play
  (JNIEnv *, jobject);

/*
 * Class:     com_syy_studio_player_Player
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_syy_studio_player_Player_stop
  (JNIEnv *, jobject);

/*
 * Class:     com_syy_studio_player_Player
 * Method:    getBufferedProgress
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_syy_studio_player_Player_getBufferedProgress
  (JNIEnv *, jobject);

/*
 * Class:     com_syy_studio_player_Player
 * Method:    getPlayProgress
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_syy_studio_player_Player_getPlayProgress
  (JNIEnv *, jobject);

/*
 * Class:     com_syy_studio_player_Player
 * Method:    seekToPosition
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_syy_studio_player_Player_seekToPosition
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_syy_studio_player_Player
 * Method:    seekCurrent
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_syy_studio_player_Player_seekCurrent
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_syy_studio_player_Player
 * Method:    beforeSeekCurrent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_syy_studio_player_Player_beforeSeekCurrent
  (JNIEnv *, jobject);

/*
 * Class:     com_syy_studio_player_Player
 * Method:    afterSeekCurrent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_syy_studio_player_Player_afterSeekCurrent
  (JNIEnv *, jobject);

/*
 * Class:     com_syy_studio_player_Player
 * Method:    resetRenderSize
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_syy_studio_player_Player_resetRenderSize
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
